export ZSH=/home/caddy/.oh-my-zsh
export PATH=/home/caddy/.config/composer/vendor/bin:$PATH
ZSH_THEME="nebirhos"
plugins=(git debian vagrant github laravel sudo taskwarrior)
source $ZSH/oh-my-zsh.sh
alias zshconf="nano ~/.zshrc"
alias omz="cd ~/.oh-my-zsh"
alias media="cd /media/caddy/Data/"
alias mysql="mysql -u root -p"
alias dotfiles="cd ~/Documents/dotfiles/"
alias size="wc -c"
alias caddy="cd ~/Documents/Websites/caddy/"
alias english="cd ~/Documents/NativeProjects/vagrant/English && code ."
alias catalyst="cd ~/Documents/NativeProjects/Rimi/src/script/ && ./rimi_server.pl"
alias install="sudo dpkg -i"
alias lan="sudo ifconfig"
alias test="vendor/bin/phpunit"
alias db="php artisan migrate:refresh --seed"
function v() {
    ( cd ~/Documents/Homestead && vagrant $* )
}
function ars() {
	( sudo service apache2 restart )
}
function srv(){
	( sudo service $* )
}
function powernex(){
	( cd ~/OSDev/PowerNex/ )
}
function english(){
	( cd ~/Documents/NativeProjects/vagrant/English/ && atom . )
}
function c() {rm -rf objs powernex.iso && echo "Clean successful" || echo "Clean failed"}
function b() {v && qemu-system-x86_64 -cdrom powernex.iso -m 2048 -monitor stdio -serial file:COM1.log -no-reboot 2>/dev/null}
function a() {addr2line -e objs/powernex.iso.objs/disk/boot/powernex.krl $1}
function initPowerNex() {
	if [ ! -f build.ninja ]; then
		dub fetch reggae
		dub run reggae -- -b ninja .
	fi
}

