export ZSH=/home/caddy/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="caddy"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git debian vagrant github laravel sudo taskwarrior)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconf="nano ~/.zshrc"
alias omz="cd ~/.oh-my-zsh"
alias media="cd /media/caddy/Data/"
alias mysql="mysql -u root -p"
alias dotfiles="cd ~/Documents/dotfiles/"
alias size="wc -c"
alias caddy="cd ~/Documents/Websites/caddy/"
alias english="cd ~/Documents/NativeProjects/vagrant/English && atom ."
alias catalyst="cd ~/Documents/NativeProjects/Rimi/src/script/ && ./rimi_server.pl"
alias install="sudo dpkg -i $"
alias lan="sudo ifconfig"
# Homestead Vagrant Environment Variables
function v() {
    ( cd ~/Documents/Homestead && vagrant $* )
}
# APT Package Manager Variables
function ars() {
	( sudo service apache2 restart )
}
# Daemons Managing Variables
function srv(){
	( sudo service $* )
}
function powernex(){
	( cd ~/OSDev/PowerNex/ )
}
function english(){
	( cd ~/Documents/NativeProjects/vagrant/English/ && atom . )
}
function c() {rm -rf objs powernex.iso && echo "Clean successful" || echo "Clean failed"}
function b() {v && qemu-system-x86_64 -cdrom powernex.iso -m 2048 -monitor stdio -serial file:COM1.log -no-reboot 2>/dev/null}
function a() {addr2line -e objs/powernex.iso.objs/disk/boot/powernex.krl $1}
function initPowerNex() {
	if [ ! -f build.ninja ]; then
		dub fetch reggae
		dub run reggae -- -b ninja .
	fi
}

