tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "php", restart_service: true
brew "composer"
brew "dnsmasq"
brew "gh"
brew "mariadb", restart_service: true
brew "nginx", restart_service: true
brew "php@7.4"
brew "redis", restart_service: true
