export PATH=$HOME/bin:/usr/local/bin:$HOME/.composer/vendor/bin:$PATH
export ZSH=/home/vagrant/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(ubuntu composer common-aliases sudo laravel4)
source $ZSH/oh-my-zsh.sh
alias zshconf="nano ~/.zshrc"
alias omz="cd ~/.oh-my-zsh"
alias db="php artisan migrate:refresh --seed"
alias test="vendor/bin/phpunit"
alias theme1="mysql -e 'use nbi3oyii;update setting set value=\"basic1\" where name=\"theme\";'"
alias theme2="mysql -e 'use nbi3oyii;update setting set value=\"basic2\" where name=\"theme\";'"
function reset(){
        mysql -e "drop database $1;create database $1;"
}
function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}${ZSH_THEME_GIT_PROMPT_CLEAN}${ZSH_THEME_GIT_PROMPT_SUFFIX}"
}
