export PATH=$HOME/bin:/usr/local/bin:/Users/mac/.composer/vendor/bin:$PATH
export PATH="/usr/local/Cellar/ruby/2.4.1_2/bin:$PATH"
export ZSH=/Users/mac/.oh-my-zsh
ZSH_THEME="caddy"
plugins=(git)
source $ZSH/oh-my-zsh.sh
alias zshconf="nano ~/.zshrc"
alias omz="cd ~/.oh-my-zsh"
alias user="mysql -uroot -e 'use english;select name, email from users limit 10;'"
alias mysql="mysql -uroot"
alias db="php artisan migrate:refresh --seed"
alias clean="find . -name .DS_Store -delete"
alias nah="git checkout -- . && git reset --hard HEAD && git clean -f"
function delete(){
	( mysql -e "use english;delete from $1;" )
}
function v(){
	( cd ~/Homestead && vagrant $* )
}
