export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:/usr/local/Cellar/nethogs/0.8.5/sbin:$PATH
export PATH="/usr/bin:/usr/local/sbin:/bin:/usr/sbin:/sbin":$PATH
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="caddy"
plugins=(git osx composer github laravel sudo)
source $ZSH/oh-my-zsh.sh
function reset() {
	mysql -e "drop database $1;create database $1;"
}
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
source ~/.aliases
